### ISSUE TITLE
Gloves crimson web double web unknown & wrongly ranked

### ISSUE THREAD

**Issue by zada273** [GODrums/cs-tierlist#1]
pattern 936 is not found in guide provided and should be tier 2 double web (looks like would be best tier 2 pattern), compared to pattern 656 (mid tier 2 listed in guide) 
![936 & 656 compared](https://github.com/GODrums/cs-tierlist/assets/149738416/20b8c71a-5811-4aa5-a02c-6eb0049911ee)

pattern 369 is listed as a tier 2 right hand 1 web in the guide, when it should be tier 3 double web and its better when compared to pattern 420 (mid tier 3 listed in guide) because its reversed so the right hand has the better web placement (right hand is more important since you hold the knife with it) 
![369 & 420 compared](https://github.com/GODrums/cs-tierlist/assets/149738416/6c3ddaf2-d58d-4a0a-8a44-4fc4179aa05d)

**Comment by GODrums** [comment]
Both suggestions seem plausible to me. 
I just added pattern 936 and changed 369 accordingly.
The changes are already live in version 1.1.3 on NPM as well as the generated JSON.

Thank you for your contribution!
